### ISSUE TITLE
Errors occurring in neovim after async updates

### ISSUE THREAD

**Issue by jonnixs** [airblade/vim-gitgutter#440]
Since commit "54209a0199bcb9f6b7c452deb0ffbc3aa60b857d" this plugin has started producing errors on startup, and on focus. Reverting to the previous commit clears the problem up.

The errors I'm seeing are:

    Error detected while processing function <SNR>157_on_exit_nvim:
    E118: Too many arguments for function: function
    Error detected while processing function <SNR>157_on_exit_nvim:
    E116: Invalid arguments for function <SNR>157_buffer_exec

Any more info needed, just ask. :)

**Comment by airblade** [comment]
Thanks for letting me know!

I can't reproduce this.  What version of nvim are you using?  And when you get these errors on startup, is that starting up with no file, or a file with changes, or something else?

**Comment by jonnixs** [comment]
Using NVIM 0.1.7.

On startup, it's only when opening with a file.

**Comment by airblade** [comment]
I'm on nvim 0.2.1 and it seems to work.  Would you be able to upgrade?

**Comment by jonnixs** [comment]
Tested and you're correct. Updating to 0.2.1 resolved the errors.

Only slight worry is that to install via apt on ubuntu, you have to add the unstable ppa, though I suppose that's for neovim to update their repositories.

Assuming there's not much point in fixing for 0.1.7, feel free to close the ticket. Thanks for the help.

**Comment by airblade** [comment]
Glad it's working for you now.

I agree, it's not ideal to have to add an unstable ppa.  However I can't summon the motivation to make it work on 0.1.7 now ;)
