### ISSUE TITLE
Gitgutter broken on nvim since 54209a0

### ISSUE THREAD

**Issue by edi9999** [airblade/vim-gitgutter#441]
Hello,

with the current commit everything works fine with nvim : f2ff232

However with commit 54209a0 (current master), I have following error when I try to exit with `zz` or `ZZ` : 

```
Error detected while processing function <SNR>98_on_exit_nvim:
line    1:
E118: Too many arguments for function: function
```

**Comment by jsl9208** [comment]
same here

**Comment by airblade** [comment]
Please could you upgrade NeoVim (see #440) and try again?

**Comment by edi9999** [comment]
Seems to be working indeed with latest version
