### ISSUE TITLE
async execute problem?

### ISSUE THREAD

**Issue by gilesorr** [airblade/vim-gitgutter#496]
> What is the latest commit SHA in your installed vim-gitgutter?

5db4a3a2a59ac730239de8dfb0c09afc89942fe7

> What vim/nvim version are you on?

$ nvim --version
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-cV3qPl/neovim-0.1.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-cV3qPl/neovim-0.1.7/build/config -I/build/neovim-cV3qPl/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-cV3qPl/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-cV3qPl/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

-1

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

Environment: Raspbian Lite, Neovim running inside tmux.

When I start Neovim, I get this:

Error detected while processing function gitgutter#init_buffer[4]..gitgutter#utility#set_repo_path:
line   16:
E118: Too many arguments for function: function
E116: Invalid arguments for function gitgutter#async#execute

At that point, the editor locks and a Ctrl-C is required to proceed.  Presumably this breaks gitgutter's load.  I also found that if the editor is left idle, it will again lock, and again require Ctrl-C to unlock it.  I can't prove that this is also gitgutter (no visual indicators like the message on start), but the behaviour is identical and when I revert to an older version both problems disappear.

This behaviour seems to apply to all files, regardless of whether they're in or out of a git repo, committed or new.

I'm now using 579f0a5 because it was working well on another machine (puts me in a 'detached head' state, but no problems otherwise).

Hope this helps.

**Comment by airblade** [comment]
That's an old version of neovim which is known to cause problems.  Are you able to install a more recent version?

**Comment by gilesorr** [comment]
You and I have had a very similar discussion before: https://github.com/airblade/vim-gitgutter/issues/443#issuecomment-338577145 .  That was about Fedora, this is Debian (stable/stretch, which mostly explains the age of the Neovim package) ...  Mind you, it's definitely diminishing returns for you to keep patching problems for old versions.  Although I'll repeat - 579f0a5 does work fine on Neovim 0.1.7.

To answer your question: aside from version pinning and/or pulling from testing/buster, no, not so easy to get a newer version.  I'll stick with 0.1.7 and your rev 579f0a5 for now.

I've pulled your latest (5db4a3a) on my Fedora machine with Neovim 0.2.2 and it is, as predicted, just fine.

I'll continue to file bug reports in the hope that they're helpful (because gitgutter is awesome).  You can fix or not depending if it's worth the effort - in this case I think you're justified in rejecting it.  You might want to document problems like this though as Debian stable is going to be around for a while: it was released in 2017-06, and stable releases tend to last two years.

Thanks!

**Comment by airblade** [comment]
Ah ok, that all makes sense.  If Neovim 0.1.7 is going to be around for a while and it's not so easy to upgrade, then I'll have a go at backward-compatibility.

I feel it's going to be a single thing that changed between 0.1.7 and more recent versions; something to do with how arguments for partials are handled, or similar.  Hopefully it won't be too much work to track down and code around.

**Comment by vivoconunxino** [comment]
same problem, PlugUpdate started it.

**Comment by airblade** [comment]
Any idea how to install neovim 0.1.7 on macOS?

**Comment by airblade** [comment]
The problem is that in neovim 0.1.7 the `function()` function does not support an optional list of arguments.

```viml
let x = function('Foo')             " ok
let x = function('Foo', ['bar'])    " not ok
```

**Comment by gilesorr** [comment]
https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula/4158763#4158763

Looks ugly - your best hope is that you didn't run "brew cleanup", but I personally run that frequently because brew's old versions take up a LOT of space.  But there are other options ...

I know you closed this, but ...

**Comment by airblade** [comment]
@gilesorr Thanks!

I'm confident the last commit fixed this problem but let me know if not (or if there are any others).

**Comment by vivoconunxino** [comment]
Working :-)
